kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: event
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event
        tier: backend
        env: development
    spec:
      containers:
      - name: event
        image: 10.200.10.1:5000/guilhermebr/event:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
        - name: API_PORT
          value: "3000"
        - name: MONGO_ENDPOINT
          value: "mongodb://mongo:27017"
        - name: MONGO_DATABASE
          value: "teamder"

---

kind: Service
apiVersion: v1
metadata:
  name: event
  labels:
    app: event
    env: development
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: event
    env: development
